---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "template.fullname" . }}-mongodb-init-js
data:
  init-mongo.js: |
    db = db.getSiblingDB("admin");
    db.auth(
      process.env.MONGO_INITDB_ROOT_USER,
      process.env.MONGO_INITDB_ROOT_PASS
    );
    db = db.getSiblingDB("unifi");
    db.createUser({
      user: process.env.MONGO_USER,
      pwd: process.env.MONGO_PASS,
      roles: [
       {role: "dbOwner", db: "unifi"},
       {role: "dbOwner", db: "unifi_stat"},
       {role: "readWrite", db: "unifi"}
    ]});
    db.getSiblingDB("unifi_stat");
    db.createUser({
      user: process.env.MONGO_USER,
      pwd: process.env.MONGO_PASS,
      roles: [
        {role: "dbOwner", db: "unifi_stat"},
        {role: "readWrite", db: "unifi_stat"}
    ]});
