---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "template.fullname" . }}-mongodb-init-js
data:
  init-mongo.js: |
    db.getSiblingDB("unifi").createUser({
      user: "{{ .Values.mongodb.username }}",
      pwd: "{{ .Values.mongodb.password }}",
      roles: [
       {role: "dbOwner", db: "unifi"},
       {role: "dbOwner", db: "unifi_stat"},
       {role: "readWrite", db: "unifi"}
    ]});
    db.getSiblingDB("unifi_stat").createUser({
      user: "{{ .Values.mongodb.username }}",
      pwd:"{{ .Values.mongodb.password }}",
      roles: [
        {role: "dbOwner", db: "unifi_stat"},
        {role: "readWrite", db: "unifi_stat"}
    ]});
